<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Doctor Report</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 13px;
            color: #333;
            margin: 0;
            padding: 20px;
            line-height: 1.5;
        }

        /* HEADER */
        .header {
            text-align: center;
            padding-bottom: 15px;
            margin-bottom: 25px;
            border-bottom: 3px solid #0d6efd;
        }

        .header h1 {
            margin: 0;
            font-size: 22px;
            color: #0d6efd;
            font-weight: bold;
        }

        .sub-title {
            font-size: 14px;
            color: #555;
            margin-top: 3px;
        }

        /* SECTION TITLE */
        .section-title {
            font-size: 16px;
            font-weight: bold;
            margin-top: 25px;
            padding-bottom: 6px;
            border-bottom: 2px solid #0d6efd;
            color: #0d6efd;
        }

        /* INFO TABLE */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th,
        td {
            padding: 8px;
            border: 1px solid #ddd;
        }

        th {
            background: #f5f8ff;
            font-weight: bold;
        }

        .label {
            background: #f1f1f1;
            width: 28%;
            font-weight: bold;
        }

        /* FOOTER */
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 11px;
            color: #666;
        }
    </style>
</head>

<body>

    <!-- HEADER -->
    <div class="header">
        <h1>Doctor Medical Report</h1>
        <div class="sub-title">Generated by Hospital Management System</div>
    </div>

    <!-- BASIC INFO -->
    <div class="section-title">Doctor Information</div>
    <table>
        <tr>
            <td class="label">Name</td>
            <td>Dr. {{ $doctor->user->name }}</td>
        </tr>
        <tr>
            <td class="label">Department</td>
            <td>{{ $doctor->department->name ?? 'N/A' }}</td>
        </tr>
        <tr>
            <td class="label">Specialization</td>
            <td>{{ $doctor->specialization }}</td>
        </tr>
        <tr>
            <td class="label">Qualification</td>
            <td>{{ $doctor->qualification }}</td>
        </tr>
        <tr>
            <td class="label">Experience</td>
            <td>{{ $doctor->experience_years }} years</td>
        </tr>
        <tr>
            <td class="label">Consultation Fee</td>
            <td>KES {{ number_format($doctor->consultation_fee) }}</td>
        </tr>
    </table>

    <!-- APPOINTMENTS -->
    @if ($doctor->appointments->count())
        <div class="section-title">Appointments</div>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Patient</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($doctor->appointments as $a)
                    <tr>
                        <td>{{ $a->appointment_date }}</td>
                        <td>{{ $a->patient->first_name . ' ' . $a->patient->last_name ?? '-' }}</td>
                        <td>{{ ucfirst($a->status) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <!-- PRESCRIPTIONS -->
    @if ($doctor->prescriptions->count())
        <div class="section-title">Prescriptions</div>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Patient</th>
                    <th>Notes</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($doctor->prescriptions as $p)
                    <tr>
                        <td>{{ $p->id }}</td>
                        <td>{{ $p->patient->first_name . ' ' . $p->patient->last_name ?? '-' }}</td>
                        <td>{{ $p->notes }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <!-- ADMISSIONS -->
    @if ($doctor->admissions->count())
        <div class="section-title">Admissions</div>
        <table>
            <thead>
                <tr>
                    <th>Patient</th>
                    <th>Ward</th>
                    <th>Bed</th>
                    <th>Admitted On</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($doctor->admissions as $ad)
                    <tr>
                        <td>{{ $ad->patient->name ?? '-' }}</td>
                        <td>{{ $ad->bed->ward->name ?? '-' }}</td>
                        <td>{{ $ad->bed->number ?? '-' }}</td>
                        <td>{{ $ad->admission_date }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <!-- FOOTER -->
    <div class="footer">
        Report generated on {{ now() }}
        <br> Hospital Management System © {{ date('Y') }}
    </div>

</body>

</html>
